theme = "catppuccin_mocha"

[editor]
line-number = "relative"
rulers = [80]
color-modes = true
bufferline = "multiple"
mouse = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = [
  "diagnostics", 
  "version-control",
  "position",
  "position-percentage",
  "selections",
  "file-type"
]

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
# transpose chars
C-t = [
  "delete_selection",
  "move_char_left",
  "paste_before",
  "move_char_right"
]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-s = "split_selection_on_newline"

# space "mode" mappings
[keys.normal.space]
q = ":quit"

[keys.normal.","]
s = "split_selection"
k = ":bc"
d = [":bc", "wclose"] # close buffer and window
# Open work notes
n = [":o ~/Dropbox/Work/notes/daily.md"]
q = ":quit"
Q = ":quit!"
"," = "remove_primary_selection"
f = ':format'

[keys.normal.backspace]
r = ":sh cargo run"
s = [":w", ":config-reload" ]
"backspace" = ":config-open"
