(straight-use-package '(org :type built-in))
(require 'org)

(with-eval-after-load 'org
  (require 'ol-man)
  (add-to-list 'org-modules 'ol-man t)
  (add-to-list 'org-modules 'org-habit t))

;;; NOTE: this was all generated by GTP-5.4 nano.

(require 'org)
(require 'cl-lib)

(defun my/org-entry-has-weight-p (&optional pos)
  "Return non-nil if POS (or point) has a non-empty WEIGHT property."
  (let ((p (or pos (point))))
    (let ((w (org-entry-get p "WEIGHT" t)))
      (and w (not (equal w ""))))))

(defun my/org-entry-weight (&optional pos)
  "Return numeric weight for POS (or point). If missing/invalid, return nil."
  (let ((w (org-entry-get (or pos (point)) "WEIGHT" t)))
    (when (and w (not (equal w "")))
      (string-to-number w))))

(defun my/org-immediate-parent-pos ()
  "Return point of immediate parent heading, or nil."
  (when (org-at-heading-p)
    (save-excursion
      (let ((target-level (1- (org-outline-level))))
        (when (= target-level (1- target-level)) ; no-op, keeps structure simple
          nil)
        (when (org-up-heading-safe)
          (when (= (org-outline-level) target-level)
            (point)))))))

(defun my/org-progress-percent (done-sum total-sum)
  "Compute integer percent from DONE-SUM and TOTAL-SUM."
  (if (<= total-sum 0.0)
      0
    (round (* 100.0 (/ done-sum total-sum)))))

(defun my/org-set-parent-progress (parent-pos pct)
  "Set PROGRESS property on PARENT-POS to PCT (as 'NN%').
   PROGRESS is created if missing."
  (with-current-buffer (marker-buffer parent-pos)
    (goto-char parent-pos)
    (org-entry-put nil "PROGRESS" (format "%d%%" pct))))

(defun my/org-child-todo-and-weight-p ()
  "If current heading is a TODO heading with numeric WEIGHT, return (todo . weight).
   If not, return nil."
  (let ((todo (org-get-todo-state)))
    (when todo
      (let ((w (my/org-entry-weight (point))))
        (when w
          (cons todo w))))))

(defun my/org-sum-weights-for-parent-children (parent-pos)
  "For PARENT-POS, sum (done-weight . total-weight) over its immediate TODO children.
   Only counts children that are TODO headings and have numeric WEIGHT."
  (with-current-buffer (marker-buffer parent-pos)
    (save-excursion
      (goto-char parent-pos)
      (let* ((parent-level (org-outline-level))
             (child-level  (1+ parent-level))
             (end           (org-end-of-subtree t))
             (done-sum      0.0)
             (total-sum     0.0))
        (save-restriction
          (narrow-to-region (point) end)
          (goto-char (point-min))
          (while (re-search-forward org-outline-regexp-bol nil t)
            (when (= (org-outline-level) child-level)
              (let ((tw (my/org-child-todo-and-weight-p)))
                (when tw
                  (let ((todo (car tw))
                        (w    (cdr tw)))
                    (setq total-sum (+ total-sum (float w)))
                    (when (member todo org-done-keywords)
                      (setq done-sum (+ done-sum (float w))))))))))

        (cons done-sum total-sum)))))

(defun my/org-weighted-progress-update-from-weighted-child ()
  "If current heading has WEIGHT, update immediate parent's PROGRESS."
  (when (and (org-at-heading-p)
             (my/org-entry-has-weight-p (point)))
    (let* ((parent-pos (my/org-immediate-parent-pos)))
      (when parent-pos
        (let* ((parent-marker (copy-marker parent-pos t))
               (sums (my/org-sum-weights-for-parent-children parent-marker))
               (done-sum (car sums))
               (total-sum (cdr sums))
               (pct (my/org-progress-percent done-sum total-sum)))
          (my/org-set-parent-progress parent-marker pct)
          (set-marker parent-marker nil))))))

(add-hook 'org-after-todo-state-change-hook
          #'my/org-weighted-progress-update-from-weighted-child)

(use-package org-tempo
  :after org
  :config
  (keymap-set org-mode-map "C-c q" #'tempo-template-org-quote))

(setq org-directory "~/Library/CLoudStorage/Dropbox/org/gtd/")
(setq org-default-notes-file "~/Library/CloudStorage/Dropbox/org/gtd/gtd.org")

(setq org-todo-keywords
      '((sequence
         "TODO(t)"
         "NEXT(n)"
         "WAIT(w)"
         "STRT(s)"
         "BLOCKED(b)"
         "REVIEW(r)"
         "|"
         "DONE(d)"
		 "CANCELED(c)")))

(setq org-image-actual-width nil)

(setq org-src-preserve-indentation nil)
(setq org-startup-indented t)
(straight-use-package
 '(org-modern-indent
   :type git
   :host github
   :repo "jdtsmith/org-modern-indent"))
(require 'org-modern-indent)
(add-hook 'org-mode-hook #'org-modern-indent-mode 90)

(setq org-hide-emphasis-markers t)

(setq org-priority-highest ?A
	  org-priority-lowest ?D)

;; for handling CSL citation languages in org exporting to latex
(straight-use-package 'citeproc)

;; use latexmk for generating pdfs from tex files
(setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))

(with-eval-after-load 'org
  (straight-use-package 'ox-typst)
  (require 'ox-typst))

(setq org-agenda-custom-commands
	  '(("g" "GTD Review"
		 ((tags "+proj+LEVEL=2"
				((org-agenda-overriding-header "Active Projects")))
		  (todo "STRT"
				((org-agenda-overriding-header "In Progress")))
		  (todo "WAIT|REVIEW|BLOCKED"
				((org-agenda-overriding-header "Waiting...")))
		  (todo "NEXT"
				((org-agenda-overriding-header "Next Actions")))
		  (tags "+DEADLINE=\"\"+SCHEDULED=\"\"+TODO=\"TODO\""
				((org-agenda-overriding-header "Inactive tasks")))))

		("d" "GTD Daily View"
		 ((agenda ""
				  ((org-agenda-overriding-header "Today")
				   (org-agenda-span 1)))
		  (todo "STRT"
				((org-agenda-overriding-header "In Progress")))
		  (todo "WAIT|REVIEW|BLOCKED"
				((org-agenda-overriding-header "Waiting...")))
		  (todo "NEXT"
				((org-agenda-overriding-header "Next Actions")))))))

(setq org-agenda-time-grid
	  '((daily today require-timed remove-match)
		(800 1000 1200 1400 1600 1800 2000)
		" ┄┄┄┄┄ "
		"┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄"))

(setq org-stuck-projects
		'("+proj-archive+LEVEL=1/-DONE" ("NEXT" "STRT") nil ""))

(advice-add 'org-agenda-quit :before 'org-save-all-org-buffers)

(setq org-refile-targets
	  '((org-agenda-files . (:regexp . "One Off"))
		(org-agenda-files . (:regexp . "Events"))
		(org-agenda-files . (:regexp . "Someday"))
		(org-agenda-files . (:regexp . "Tasks"))
		(org-agenda-files . (:tag . "proj"))))

(setq org-tag-alist
      '((:startgroup)
        ("proj" . ?p)
        ("area" . ?a)
        (:endgroup)

        ;; mental/emotional level
        (:startgroup)
        ("@lowenergy" . ?l)
        ("@highenergy" . ?h)
        (:endgroup)

        ;; locations
        (:startgroup)
        ("@Church" . ?C)
        ("@Work" . ?W)
        ("@Transit" . ?T)
        ("@Home" . ?H)
        ("@Anywhere" . ?A)
        ("@Outsize" . ?O)
        (:endgroup)

        ;; devices
        (:startgroup)
        ("@Laptop" . ?L)
        ("@Phone" . ?P)
        (:endgroup)))

(setq org-agenda-include-diary t)
(setq org-agenda-restore-windows-after-quit t)
(setq org-agenda-skip-deadline-if-done t
      org-agenda-skip-scheduled-if-done t)
(setq org-agenda-category-icon-alist nil)
(setq org-columns-default-format "%TODO %3PRIORITY %45ITEM %16SCHEDULED %TAGS")
(add-to-list 'org-agenda-category-icon-alist
             '(".*" '(space . (:width (18)))))

(add-to-list 'org-agenda-files (concat
								org-directory
								"gtd.org"))
(add-to-list 'org-agenda-files (concat
								org-directory
								"events.org"))
(add-to-list 'org-agenda-files (concat
								org-directory
								"pull_requests.org"))

;; (straight-use-package 'org-super-agenda)
;; (setq org-super-agenda-groups
;; '(
;; 	(:name "Today"
;; 	       :time-grid t
;; 	       :todo '("TODO" "WORKING"))))

(global-set-key (kbd "C-c o c") #'org-capture)
(global-set-key (kbd "C-c o a") #'org-agenda)

(setq org-tag-alist '((:startgroup)
					  ("@Work" . ?w)
					  ("@Church" . ?c)
					  ("@Home" . ?h)
					  ("@Errands" . ?e)
					  (:endgroup)
					  ("security" . ?s)
					  ("pastoral" . ?p)))

(defun my/org-capture-schedule ()
  "Prompt for [t]oday or [d]ate pciker; return a SCHEDULED line."
  (let* ((ch (read-char-choice "Schedule: [t]oday  [d]ate " '(?t ?d)))
		 (time (pcase ch
				 (?t (current-time))
				 (?d (org-time-string-to-time
					  (org-read-date nil nil nil "Date: "))))))
	(concat "SCHEDULED: " (format-time-string "<%Y-%m-%d %a>" time))))


(setq org-capture-templates
	  `(("i" "Inbox   - things that may need attention later" entry (file "~/Library/CloudStorage/Dropbox/org/gtd/inbox.org")
         "* %?\n/Entered on/ %U")
		("r" "Pull request review" entry
		 (file+headline "~/Library/CloudStorage/Dropbox/org/gtd/pull_requests.org" "Pull requests")
		 "* NEXT [[%c][%(gh-get-pr-title (current-kill 0))]]"
		 :immediate-finish t)
		("p" "Project - new project" entry
		 (file+headline org-default-notes-file "Projects")
		 "* %^{project title} %(org-set-tags \"proj\")\n** Notes\n\n** Tasks\n*** TODO %?")
		("t" "Task" entry
		 (file+headline org-default-notes-file "Tasks")
		 "* TODO %^{Task} %^g\n%(my/org-capture-schedule)\n%?"
		 :empty-lines-before 1
		 :kill-buffer t)))

(setq org-structure-template-alist
      '(("s" . "src")
        ("e" . "src emacs-lisp")
        ("b" . "src bash")
		("q" . "quote")
        ("t" . "src emacs-lisp :tangle FILENAME :mkdirp yes")))

(require 'ox-publish)

(setq org-publish-use-timestamps-flag nil)

;; Don't show validation link
(setq org-html-validation-link nil)
;; Use our own scripts
(setq org-html-head-include-scripts nil)
;; Use our own styles
(setq org-html-head-include-default-style nil)

;; this allows us to get syntax highlighting in source blocks exported to html
(straight-use-package 'htmlize)

(setq org-publish-project-alist
  (list (list "blog"
          :components (list "blog-org" "blog-static"))
    (list "blog-org"
          :base-directory "~/blog/org"
          :publishing-directory "~/blog/public"
          :auto-sitemap nil
          :recursive t
          :with-broken-links t
                  :with-creator t
          :section-numbers nil
          :exclude "README"
          :export-exclude-tags (list "draft")
          :with-author "Jon Harder"
          :with-toc nil
          :html-htmlize-output-type 'inline-css
          :html-doctype "html5"
          :html-html5-fancy t
          :html-preamble nil
          :html-postamble nil)
    (list "blog-static"
          :base-directory "~/blog/org/"
          :base-extension "css\\|ico\\|png\\|jpg\\|jpeg\\|gif"
          :publishing-directory "~/blog/public/"
          :recursive t
          :publishing-function #'org-publish-attachment)))

(setq org-hide-emphasis-markers t)

(straight-use-package 'org-modern)
(setq org-modern-fold-stars
      '(("▶" . "▼")
        ("▷" . "▽")
		;; this symbol is not present in many fonts, including mine
		;; the author proposes that the fonts should include the symbol
		;; here is my workaround
		;; courtesy of https://github.com/minad/org-modern/issues/232
        ;; ("⯈" . "⯆")
        ("▷" . "▽")
        ("▹" . "▿")
        ("▸" . "▾"))) 
(with-eval-after-load 'org (global-org-modern-mode))

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (python . t)
   (calc . t)
   (shell . t)))

(straight-use-package 'toc-org)
(add-hook 'org-mode-hook 'toc-org-mode)

(straight-use-package 'literate-calc-mode)
(add-hook 'org-mode-hook #'literate-calc-minor-mode)

(use-package citar
  :straight t
  :custom
  (citar-bibliography '("~/Library/CloudStorage/Dropbox/org/wiki/bibliography.bib"))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  :bind
  (:map org-mode-map :package org ("C-c b" . #'org-cite-insert)))

(provide 'my-org)
