#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Jon Harder"
email = "jharder@kipsu.com"

[ui]
default-command = "log"
editor = "emacsclient -a ''"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@ & bookmarks())", "--to", "@"]
push = ["git", "push", "-r", "@"]