#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Jon Harder"
email = "jharder@kipsu.com"

[ui]
default-command = "log"
editor = "emacsclient -a ''"
# try to use difft by default
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[ui.movement]
edit = true

[remotes.origin]
# auto-track-bookmarks = "glob:*"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@ & bookmarks())", "--to", "@"]
p = ["git", "push", "-r", "@"]
f = ["git", "fetch"]
d = ["describe"]
###################################################################
# alias: "log trunk"
# show changes from trunk() to the current working change.
# usefull for large, branch heavy codebases with lots of large,
# long lived feature branches
lt = ["log", "-r", "trunk()..@ | trunk()"]
